drop database if exists transactions;
create database if not exists transactions;
use transactions;
drop table if exists stock_info;
create table stock_info (
  stockname VARCHAR(30) NOT NULL,
  date DATETIME NOT NULL,
  open float,
  high float,
  low float,
  close float,
  volume float,
  sma5 float,
  sma10 float,
  sma15 float,
  sma20 float,
  ema5 float,
  ema10 float,
  ema15 float,
  ema20 float,
  upperband float,
  middleband float,
  lowerband float,
  HT_TRENDLINE float,
  KAMA10 float,
  KAMA20 float,
  KAMA30 float,
  SAR float,
  TRIMA5 float,
  TRIMA10 float,
  TRIMA20 float,
  ADX5 float,
  ADX10 float,
  ADX20 float,
  APO float,
  CCI5 float,
  CCI10 float,
  CCI15 float,
  macd510 float,
  macd520 float,
  macd1020 float,
  macd1520 float,
  macd1226 float,
  MOM10 float,
  MOM15 float,
  MOM20 float,
  ROC5 float,
  ROC10 float,
  ROC20 float,
  PPO float,
  RSI14 float,
  RSI8 float,
  slowk float,
  slowd float,
  fastk float,
  fastd float,
  fastksr float,
  fastdsr float,
  ULTOSC float,
  WILLR float,
  ATR float,
  Trange float,
  TYPPRICE float,
  HT_DCPERIOD float,
  BETA float,
  PRIMARY KEY(stockname, date)
) engine=ReplacingMergeTree
ORDER BY (stockname, date);